name: Deploy api to Elastic Beanstalk staging

on:
  push:
    branches:
      - feat/cicd

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Change to API Directory
        run: cd api

      - name: Install Dependencies
        run: npm install
        working-directory: ./api

      - name: Build
        run: npm run build
        working-directory: ./api

      - name: Deploy to Elastic Beanstalk
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
          AWS_REGION: "us-east-1"
          APPLICATION_NAME: "PredictionBox-api-staging"
          ENVIRONMENT_NAME: "PredictionBox-api-staging-env"
        run: |
          cd api
          pip install awsebcli
          eb init -p node.js $APPLICATION_NAME --region $AWS_REGION
          eb deploy $ENVIRONMENT_NAME
